package gob.issste.gys.repository;

import java.util.List;

import gob.issste.gys.model.CifrasDeImpuestos;
import gob.issste.gys.model.CifrasDeImpuestosPorRepresentacion;
import gob.issste.gys.model.DatosPensionAlimenticia;
import gob.issste.gys.model.DetalleCifrasDeImpuestos;
import gob.issste.gys.model.DetalleCifrasDeImpuestosConPA;
import gob.issste.gys.model.DetalleCifrasDeImpuestosPorRep;
import gob.issste.gys.model.LayoutSpep;

public interface IAdminRepository {

	public String QUERY_CONSULTA_LAYOUT_SPEP_ORD = "Select A.rfc, A.nombre, A.apellidoPat, A.apellidoMat, A.id_beneficiario,\r\n"
												+ "  B.percepciones, B.isr, B.pension_1, B.pension_2, B.pension_3, B.pension_4,\r\n"
												+ "  B.guardia, B.id_clave_servicio_g, B.id_centro_trabajo_g,\r\n"
												+ "  B.suplencia, B.id_clave_servicio_s, B.id_centro_trabajo_s\r\n"
												+ "From (\r\n"
												+ "  Select rfc, MAX(nombre) nombre, MAX(apellidopat) apellidopat, MAX(apellidomat) apellidomat, MAX(iddelegacion) iddelegacion,\r\n"
												+ "    MAX(codigo_postal) codigo_postal, MAX(curp) curp, MAX(id_beneficiario) id_beneficiario\r\n"
												+ "  From gys_bolsatrabajo\r\n"
												+ "  Group By rfc\r\n"
												+ ") A, (\r\n"
												+ "  Select anio_ejercicio, mes_ejercicio, id_tipo_paga, id_ordinal, IMP.rfc, percepciones, isr, casos,\r\n"
												+ "      pension_1, pension_2, pension_3, pension_4, \r\n"
												+ "      SUM(NVL(GE.casos_gua,0)) casos_gua, SUM(NVL(guardia,0)) guardia, MAX(serv_gua) id_clave_servicio_g, MAX(ct_gua) id_centro_trabajo_g,\r\n"
												+ "      SUM(NVL(SE.casos_sup,0)) casos_sup, SUM(NVL(suplencia,0)) suplencia, MAX(serv_sup) id_clave_servicio_s, MAX(ct_sup) id_centro_trabajo_s\r\n"
												+ "  From gys_externos_isr2 IMP\r\n"
												+ "  Left Join (\r\n"
												+ "      Select rfc, fec_paga, NVL(COUNT(*), 0) casos_gua, NVL(SUM(importe), 0) guardia, MAX(id_clave_servicio) serv_gua, MAX(id_centro_trabajo) ct_gua\r\n"
												+ "      From gys_guardias_ext\r\n"
												+ "      Group By rfc, fec_paga\r\n"
												+ "  ) GE\r\n"
												+ "  ON IMP.rfc = GE.rfc\r\n"
												+ "    And GE.fec_paga Between IMP.fec_min And IMP.fec_max\r\n"
												+ "  Left Join (\r\n"
												+ "      Select rfc, fec_paga, NVL(COUNT(*), 0) casos_sup, NVL(SUM(importe), 0) suplencia, MAX(id_clave_servicio) serv_sup, MAX(id_centro_trabajo) ct_sup\r\n"
												+ "      From gys_suplencias_ext\r\n"
												+ "      Group By rfc, fec_paga\r\n"
												+ "  ) SE\r\n"
												+ "  ON IMP.rfc = SE.rfc\r\n"
												+ "    And SE.fec_paga Between IMP.fec_min And IMP.fec_max\r\n"
												+ "  Where anio_ejercicio = ? And mes_ejercicio = ? And id_tipo_paga = ? And id_ordinal = ?\r\n"
												+ "  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, id_ordinal, IMP.rfc, percepciones, isr, casos,\r\n"
												+ "      pension_1,pension_2,pension_3,pension_4\r\n"
												+ ") B\r\n"
												+ "Where A.rfc = B.rfc";

	List<LayoutSpep> consultaLayoutSPEP(Integer anio, Integer mes, Integer tipoPaga, Integer id_ordinal);

	public String QUERY_CONSULTA_LAYOUT_SPEP_REP = "Select A.rfc, A.nombre, A.apellidoPat, A.apellidoMat, A.id_beneficiario, A.consecutivo,\r\n"
												+ "  B.percepciones, B.isr, B.pension_1, B.pension_2, B.pension_3, B.pension_4,\r\n"
												+ "  B.pension_1+B.pension_2+B.pension_3+B.pension_4 suma_pension,\r\n"
												+ "  B.fecha_inicio fec_inicio, B.fecha_fin fec_fin,\r\n"
												+ "  B.id_representacion, B.n_representacion, B.id_centro_trabajo, B.n_centro_trabajo, B.id_clave_servicio, B.n_clave_servicio, ur, ct, aux,\r\n"
												+ "  B.guardia, B.id_puesto_plaza_g, B.n_puesto_plaza_g,\r\n"
												+ "  B.ff_g, B.ai_g, B.ap_g, B.sp_g,\r\n"
												+ "  B.suplencia, B.id_puesto_plaza_s, B.n_puesto_plaza_s,\r\n"
												+ "  B.ff_s, B.ai_s, B.ap_s, B.sp_s\r\n"
												+ "From (\r\n"
												+ "  Select rfc, MAX(nombre) nombre, MAX(apellidopat) apellidopat, MAX(apellidomat) apellidomat, MAX(iddelegacion) iddelegacion,\r\n"
												+ "    MAX(codigo_postal) codigo_postal, MAX(curp) curp, MAX(id_beneficiario) id_beneficiario,  MAX(consecutivo) consecutivo\r\n"
												+ "  From gys_bolsatrabajo\r\n"
												+ "  Group By rfc\r\n"
												+ ") A, (\r\n"
												+ "  Select anio_ejercicio, mes_ejercicio, id_tipo_paga, id_ordinal, IMP.rfc, percepciones, isr, casos,\r\n"
												+ "      NVL(pension_1,0) pension_1, NVL(pension_2,0) pension_2, NVL(pension_3,0) pension_3, NVL(pension_4,0) pension_4, IMP.id_centro_trabajo, n_centro_trabajo, O.ur, O.ct, O.aux,\r\n"
												+ "      IMP.id_delegacion id_representacion, C.n_div_geografica n_representacion, IMP.id_clave_servicio, n_clave_servicio,\r\n"
												+ "      (Select MIN(fec_inicio) From gys_fechas_control P Where P.fec_pago Between IMP.fec_min And IMP.fec_max ) fecha_inicio, \r\n"
												+ "      (Select MAX(fec_fin)    From gys_fechas_control P Where P.fec_pago Between IMP.fec_min And IMP.fec_max ) fecha_fin,\r\n"
												+ "      SUM(NVL(GE.casos_gua,0)) casos_gua, SUM(NVL(guardia,0)) guardia, MAX(NVL(puesto_gua,'')) id_puesto_plaza_g, MAX(NVL(n_puesto_gua,'')) n_puesto_plaza_g,\r\n"
												+ "      MAX(ff_g) ff_g, MAX(ai_g) ai_g, MAX(ap_g) ap_g, MAX(sp_g) sp_g,\r\n"
												+ "      SUM(NVL(SE.casos_sup,0)) casos_sup, SUM(NVL(suplencia,0)) suplencia, MAX(NVL(puesto_sup,'')) id_puesto_plaza_s, MAX(NVL(n_puesto_sup,'')) n_puesto_plaza_s,\r\n"
												+ "      MAX(ff_s) ff_s, MAX(ai_s) ai_s, MAX(ap_s) ap_s, MAX(sp_s) sp_s\r\n"
												+ "  From gys_externos_isr2 IMP\r\n"
												+ "  Inner Join m4t_centros_trab B\r\n"
												+ "  ON IMP.id_centro_trabajo = B.id_centro_trabajo\r\n"
												+ "  Inner Join m4t_conv_ct O\r\n"
												+ "  ON B.id_centro_trabajo = O.ct5\r\n"
												+ "  Inner Join m4t_delegaciones C\r\n"
												+ "  ON IMP.id_delegacion = C.id_div_geografica\r\n"
												+ "  Inner Join m4t_clave_servicio S\r\n"
												+ "  ON S.id_empresa = '01' And S.id_sociedad = '01' And IMP.id_clave_servicio = S.id_clave_servicio\r\n"
												+ "  Left Join (\r\n"
												+ "      Select rfc, D.id_div_geografica id_delegacion, fec_paga, NVL(COUNT(*), 0) casos_gua, NVL(SUM(importe), 0) guardia, NVL(MAX(GE.id_puesto_plaza),'') puesto_gua, NVL(MAX(n_puesto_plaza),'') n_puesto_gua,\r\n"
												+ "      MAX(ff) ff_g, MAX(ai) ai_g, MAX(ap) ap_g, MAX(sp) sp_g\r\n"
												+ "      From gys_guardias_ext GE, m4t_puestos_plaza PU, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A, gys_fechas_control F, gys_presupuesto P, gys_presupuesto_prog PR, m4t_clave_servicio SER\r\n"
												+ "      Where GE.id_puesto_plaza = PU.id_puesto_plaza\r\n"
												+ "        AND GE.id_clave_servicio = SER.id_clave_servicio\r\n"
												+ "        And GE.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "        AND C.id_centro_trabajo = P.id_centro_trabajo\r\n"
												+ "        AND P.id_centro_trabajo = GE.id_centro_trabajo\r\n"
												+ "        AND D.id_div_geografica = P.iddelegacion\r\n"
												+ "        AND D.id_area_generadora = C.id_area_generadora\r\n"
												+ "        And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "        And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "        And fec_paga = F.fec_pago\r\n"
												+ "        And P.quincena = F.quincena\r\n"
												+ "        And P.id = PR.idpresupuesto\r\n"
												+ "        And PU.id_empresa = '01' And PU.id_sociedad = '01'\r\n"
												+ "        And GE.id IN (Select id_guardia From gys_autorizacion_guardias Where estatus2=3 And id_tipo='GE')\r\n"
												+ "		   And C.id_area_generadora = ( Select id_area_generadora From m4t_delegaciones Where id_div_geografica = ? )\r\n"
												+ "        AND P.idtipopresup = 2 \r\n"
												+ "      Group By rfc, D.id_div_geografica, fec_paga\r\n"
												+ "  ) GE\r\n"
												+ "  ON IMP.rfc = GE.rfc\r\n"
												+ "    And IMP.id_delegacion = GE.id_delegacion\r\n"
												+ "    And GE.fec_paga Between IMP.fec_min And IMP.fec_max\r\n"
												+ "  Left Join (\r\n"
												+ "      Select rfc, D.id_div_geografica id_delegacion, fec_paga, NVL(COUNT(*), 0) casos_sup, NVL(SUM(importe), 0) suplencia, NVL(MAX(SE.id_puesto_plaza),'') puesto_sup, NVL(MAX(n_puesto_plaza),'') n_puesto_sup,\r\n"
												+ "      MAX(ff) ff_s, MAX(ai) ai_s, MAX(ap) ap_s, MAX(sp) sp_s\r\n"
												+ "      From gys_suplencias_ext SE, m4t_puestos_plaza PU, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A, gys_fechas_control F, gys_presupuesto P, gys_presupuesto_prog PR, m4t_clave_servicio SER\r\n"
												+ "      Where SE.id_puesto_plaza = PU.id_puesto_plaza\r\n"
												+ "        AND SE.id_clave_servicio = SER.id_clave_servicio\r\n"
												+ "        And SE.id_centro_trabajo = C.id_centro_trabajo\r\n"
												+ "        AND C.id_centro_trabajo = P.id_centro_trabajo\r\n"
												+ "        AND P.id_centro_trabajo = SE.id_centro_trabajo\r\n"
												+ "        AND D.id_div_geografica = P.iddelegacion\r\n"
												+ "        AND D.id_area_generadora = C.id_area_generadora\r\n"
												+ "        And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "        And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "        And fec_paga = F.fec_pago\r\n"
												+ "        And P.quincena = F.quincena\r\n"
												+ "        And P.id = PR.idpresupuesto\r\n"
												+ "        And PU.id_empresa = '01' And PU.id_sociedad = '01'\r\n"
												+ "        And SE.id IN (Select id_suplencia From gys_autorizacion_suplencias Where estatus2=3 And id_tipo='SE')\r\n"
												+ "		   And C.id_area_generadora = ( Select id_area_generadora From m4t_delegaciones Where id_div_geografica = ? )\r\n"
												+ "        AND P.idtipopresup = 4 \r\n"
												+ "      Group By rfc, D.id_div_geografica, fec_paga\r\n"
												+ "  ) SE\r\n"
												+ "  ON IMP.rfc = SE.rfc\r\n"
												+ "    And IMP.id_delegacion = SE.id_delegacion\r\n"
												+ "    And SE.fec_paga Between IMP.fec_min And IMP.fec_max \r\n"
												+ "  Where anio_ejercicio = ? And mes_ejercicio = ? And id_tipo_paga = ? And id_ordinal = ?\r\n"
												+ "    And B.id_area_generadora = ( Select id_area_generadora From m4t_delegaciones Where id_div_geografica = ? )\r\n"
												+ "  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, id_ordinal, IMP.rfc, percepciones, isr, casos,\r\n"
												+ "      pension_1,pension_2,pension_3,pension_4, IMP.id_centro_trabajo, n_centro_trabajo, IMP.id_delegacion, C.n_div_geografica, IMP.id_clave_servicio,\r\n"
												+ "      n_clave_servicio, ur, ct, aux, fecha_inicio, fecha_fin\r\n"
												+ ") B\r\n"
												+ "Where A.rfc = B.rfc \r\n"
												+ "Order By B.id_representacion, B.id_centro_trabajo, A.rfc";

	List<LayoutSpep> consultaLayoutSPEP_X_Rep(Integer anio, Integer mes, Integer tipoPaga, Integer id_ordinal, String id_rep);

	public String STMT_CALCULA_ISR_NON			= "Insert Into gys_externos_isr2 ( anio_ejercicio, mes_ejercicio, id_tipo_paga, id_ordinal,\r\n"
												+ "rfc, id_delegacion, casos, percepciones, isr, id_clave_servicio, id_centro_trabajo, fec_min, fec_max )\r\n"
												+ "Select anio_ejercicio, mes_ejercicio, id_tipo_paga,\r\n"
												+ "(Select NVL(MAX(id_ordinal),0) + 1 From gys_externos_isr2 Where anio_ejercicio = ? And mes_ejercicio = ? And id_tipo_paga = 4) id_ordinal,\r\n"
												+ "rfc, id_delegacion, SUM(casos) casos, SUM(importe) percep, _get_ispt_( SUM(importe) * 2 ) / 2 isr,\r\n"
												+ "MAX(id_clave_servicio) id_clave_servicio, MAX(id_centro_trabajo) id_centro_trabajo, MIN(fec_min) fec_min,  MAX(fec_max) fec_max\r\n"
												+ "From (\r\n"
												+ "  Select\r\n"
												+ "    anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
												+ "    MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
												+ "  From gys_guardias_ext G, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "  Where G.fec_paga = F.fec_pago\r\n"
												+ "    And G.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "    And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "    And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "    And anio_ejercicio = ?\r\n"
												+ "    And mes_ejercicio = ?\r\n"
												+ "    And id_tipo_paga = 4\r\n"
												+ "    And F.estatus = 3\r\n"
												+ "    And G.id IN (Select id_guardia From gys_autorizacion_guardias Where estatus2=3)\r\n"
												+ "  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
												+ "  UNION ALL\r\n"
												+ "  Select\r\n"
												+ "    anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
												+ "    MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
												+ "  From gys_suplencias_ext S, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "  Where S.fec_paga = F.fec_pago\r\n"
												+ "    And S.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "    And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "    And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "    And anio_ejercicio = ?\r\n"
												+ "    And mes_ejercicio = ?\r\n"
												+ "    And id_tipo_paga = 4\r\n"
												+ "    And F.estatus = 3\r\n"
												+ "    And S.id IN (Select id_suplencia From gys_autorizacion_suplencias Where estatus2=3)\r\n"
												+ "  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
												+ ") Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion";

	int calcula_isr_non(Integer anio, Integer mes);

	public String STMT_CALCULA_ISR_NON_BY_DELEG
			= "Insert Into gys_externos_isr2 ( anio_ejercicio, mes_ejercicio, id_tipo_paga, id_ordinal,\r\n"
			+"rfc, id_delegacion, casos, percepciones, isr, id_clave_servicio, id_centro_trabajo, fec_min, fec_max )\r\n"
			+"Select anio_ejercicio, mes_ejercicio, id_tipo_paga,\r\n"
			+"(Select NVL(MAX(id_ordinal),0) + 1 From gys_externos_isr2 Where anio_ejercicio = ? And mes_ejercicio = ? And id_tipo_paga = 4) id_ordinal,\r\n"
			+"rfc, id_delegacion, SUM(casos) casos, SUM(importe) percep, _get_ispt_( SUM(importe) * 2 ) / 2 isr,\r\n"
			+"MAX(id_clave_servicio) id_clave_servicio, MAX(id_centro_trabajo) id_centro_trabajo, MIN(fec_min) fec_min,  MAX(fec_max) fec_max\r\n"
			+"From (\r\n"
			+"  Select\r\n"
			+"    anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
			+"    MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
			+"  From gys_guardias_ext G, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A, gys_delegacionesporfecha DF\r\n"
			+"  Where G.fec_paga = F.fec_pago\r\n"
			+"    And F.id = DF.idfecha\r\n"
			+"    AND DF.iddelegacion = D.id_div_geografica\r\n"
			+"    And G.id_centro_trabajo=C.id_centro_trabajo\r\n"
			+"    And C.id_area_generadora = A.id_area_generadora\r\n"
			+"    And A.id_area_generadora=D.id_area_generadora\r\n"
			+"    And anio_ejercicio = ?\r\n"
			+"    And mes_ejercicio = ?\r\n"
			+"    And id_tipo_paga = 4\r\n"
			+"    And DF.estatus = 3\r\n"
			+"    And G.id IN (Select id_guardia From gys_autorizacion_guardias Where estatus2=3)\r\n"
			+"    And C.id_area_generadora = ( Select id_area_generadora From m4t_delegaciones Where id_div_geografica = ? )\r\n"
			+"    Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
			+"  UNION ALL\r\n"
			+"  Select\r\n"
			+"    anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
			+"    MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
			+"  From gys_suplencias_ext S, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A, gys_delegacionesporfecha DF\r\n"
			+"  Where S.fec_paga = F.fec_pago\r\n"
			+"  	And F.id = DF.idfecha\r\n"
			+"    AND DF.iddelegacion = D.id_div_geografica\r\n"
			+"    And S.id_centro_trabajo=C.id_centro_trabajo\r\n"
			+"    And C.id_area_generadora = A.id_area_generadora\r\n"
			+"    And A.id_area_generadora=D.id_area_generadora\r\n"
			+"    And anio_ejercicio = ?\r\n"
			+"    And mes_ejercicio = ?\r\n"
			+"    And id_tipo_paga = 4\r\n"
			+"    And DF.estatus = 3\r\n"
			+"    And S.id IN (Select id_suplencia From gys_autorizacion_suplencias Where estatus2=3)\r\n"
			+"    And C.id_area_generadora = ( Select id_area_generadora From m4t_delegaciones Where id_div_geografica = ? )\r\n"
			+"  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
			+") Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion";

	int calcula_isr_non_by_deleg(Integer anio, Integer mes, String idDeleg);


	public String STMT_CALCULA_ISR_PAR_BY_DELEG	= "Insert Into gys_externos_isr2 ( anio_ejercicio, mes_ejercicio, id_tipo_paga, id_ordinal,\r\n"
		  + "rfc, id_delegacion, casos, percepciones, isr, id_clave_servicio, id_centro_trabajo, fec_min, fec_max )\r\n"
		  + "Select \r\n"
		  + "  A.anio_ejercicio, A.mes_ejercicio, A.id_tipo_paga, \r\n"
		  + "  (Select NVL(MAX(id_ordinal),0) + 1 From gys_externos_isr2 Where anio_ejercicio = ? And mes_ejercicio = ? And id_tipo_paga = 1) id_ordinal,\r\n"
		  + "  A.rfc, A.id_delegacion, SUM(A.casos) casos, SUM(A.percep) percep, SUM(_get_ispt_(percep + NVL(percepciones, 0)) - NVL(N.isr, 0)) isr, \r\n"
		  + "  MAX(A.id_clave_servicio) id_clave_servicio, MAX(A.id_centro_trabajo) id_centro_trabajo, MIN(fec_min) fec_min,  MAX(fec_max) fec_max\r\n"
		  + "From (\r\n"
		  + "  Select anio_ejercicio, mes_ejercicio, id_tipo_paga,\r\n"
		  + "    rfc, id_delegacion, SUM(casos) casos, SUM(importe) percep, _get_ispt_( SUM(importe) * 2 ) / 2 isr,\r\n"
		  + "    MAX(id_clave_servicio) id_clave_servicio, MAX(id_centro_trabajo) id_centro_trabajo, MIN(fec_min) fec_min,  MAX(fec_max) fec_max\r\n"
		  + "  From (\r\n"
		  + "    Select\r\n"
		  + "      anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
		  + "      MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
		  + "    From gys_guardias_ext G, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A, gys_delegacionesporfecha DF\r\n"
		  + "    Where G.fec_paga = F.fec_pago\r\n"
	    	+ "  	And F.id = DF.idfecha\r\n"
		  + "      And G.id_centro_trabajo=C.id_centro_trabajo\r\n"
		  + "      And C.id_area_generadora = A.id_area_generadora\r\n"
		  + "      And A.id_area_generadora=D.id_area_generadora\r\n"
		  + "      And anio_ejercicio = ?\r\n"
		  + "      And mes_ejercicio = ?\r\n"
		  + "      And id_tipo_paga = 1\r\n"
		  + "      And F.estatus = 3\r\n"
		  + "      And G.id IN (Select id_guardia From gys_autorizacion_guardias Where estatus2=3)\r\n"
		  + "      And C.id_area_generadora = ( Select id_area_generadora From m4t_delegaciones Where id_div_geografica = ? )\r\n"
		  + "    Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
		  + "    UNION ALL\r\n"
		  + "    Select\r\n"
		  + "      anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
		  + "      MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
		  + "    From gys_suplencias_ext S, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A, gys_delegacionesporfecha DF\r\n"
		  + "    Where S.fec_paga = F.fec_pago\r\n"
			+"  	And F.id = DF.idfecha\r\n"
		  + "      And S.id_centro_trabajo=C.id_centro_trabajo\r\n"
		  + "      And C.id_area_generadora = A.id_area_generadora\r\n"
		  + "      And A.id_area_generadora=D.id_area_generadora\r\n"
		  + "      And anio_ejercicio = ?\r\n"
		  + "      And mes_ejercicio = ?\r\n"
		  + "      And id_tipo_paga = 1\r\n"
		  + "      And F.estatus = 3\r\n"
		  + "      And S.id IN (Select id_suplencia From gys_autorizacion_suplencias Where estatus2=3)\r\n"
		  + "      And C.id_area_generadora = ( Select id_area_generadora From m4t_delegaciones Where id_div_geografica = ? )\r\n"
		  + "    Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
		  + "  ) Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion\r\n"
		  + ") A Left Outer Join (\r\n"
		  + "  Select anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion, SUM(percepciones) percepciones, SUM(isr) isr\r\n"
		  + "  From gys_externos_isr2\r\n"
		  + "  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion\r\n"
		  + ") N\r\n"
		  + "  ON A.anio_ejercicio=N.anio_ejercicio\r\n"
		  + "    And A.mes_ejercicio=N.mes_ejercicio\r\n"
		  + "    And A.rfc=N.rfc\r\n"
		  + "    And A.id_delegacion=N.id_delegacion\r\n"
		  + "    And N.id_tipo_paga=4\r\n"
		  + "Group By A.anio_ejercicio, A.mes_ejercicio, A.id_tipo_paga, A.rfc, A.id_delegacion";
	int calcula_isr_par_by_deleg(Integer anio, Integer mes, String idDeleg);


	public String STMT_CALCULA_ISR_PAR			= "Insert Into gys_externos_isr2 ( anio_ejercicio, mes_ejercicio, id_tipo_paga, id_ordinal,\r\n"
												+ "rfc, id_delegacion, casos, percepciones, isr, id_clave_servicio, id_centro_trabajo, fec_min, fec_max )\r\n"
												+ "Select \r\n"
												+ "  A.anio_ejercicio, A.mes_ejercicio, A.id_tipo_paga, \r\n"
												+ "  (Select NVL(MAX(id_ordinal),0) + 1 From gys_externos_isr2 Where anio_ejercicio = ? And mes_ejercicio = ? And id_tipo_paga = 1) id_ordinal,\r\n"
												+ "  A.rfc, A.id_delegacion, SUM(A.casos) casos, SUM(A.percep) percep, SUM(_get_ispt_(percep + NVL(percepciones, 0)) - NVL(N.isr, 0)) isr, \r\n"
												+ "  MAX(A.id_clave_servicio) id_clave_servicio, MAX(A.id_centro_trabajo) id_centro_trabajo, MIN(fec_min) fec_min,  MAX(fec_max) fec_max\r\n"
												+ "From (\r\n"
												+ "  Select anio_ejercicio, mes_ejercicio, id_tipo_paga,\r\n"
												+ "    rfc, id_delegacion, SUM(casos) casos, SUM(importe) percep, _get_ispt_( SUM(importe) * 2 ) / 2 isr,\r\n"
												+ "    MAX(id_clave_servicio) id_clave_servicio, MAX(id_centro_trabajo) id_centro_trabajo, MIN(fec_min) fec_min,  MAX(fec_max) fec_max\r\n"
												+ "  From (\r\n"
												+ "    Select\r\n"
												+ "      anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
												+ "      MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
												+ "    From gys_guardias_ext G, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "    Where G.fec_paga = F.fec_pago\r\n"
												+ "      And G.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "      And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "      And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "      And anio_ejercicio = ?\r\n"
												+ "      And mes_ejercicio = ?\r\n"
												+ "      And id_tipo_paga = 1\r\n"
												+ "      And F.estatus = 3\r\n"
												+ "      And G.id IN (Select id_guardia From gys_autorizacion_guardias Where estatus2=3)\r\n"
												+ "    Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
												+ "    UNION ALL\r\n"
												+ "    Select\r\n"
												+ "      anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
												+ "      MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
												+ "    From gys_suplencias_ext S, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "    Where S.fec_paga = F.fec_pago\r\n"
												+ "      And S.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "      And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "      And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "      And anio_ejercicio = ?\r\n"
												+ "      And mes_ejercicio = ?\r\n"
												+ "      And id_tipo_paga = 1\r\n"
												+ "      And F.estatus = 3\r\n"
												+ "      And S.id IN (Select id_suplencia From gys_autorizacion_suplencias Where estatus2=3)\r\n"
												+ "    Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
												+ "  ) Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion\r\n"
												+ ") A Left Outer Join (\r\n"
												+ "  Select anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion, SUM(percepciones) percepciones, SUM(isr) isr\r\n"
												+ "  From gys_externos_isr2\r\n"
												+ "  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion\r\n"
												+ ") N\r\n"
												+ "  ON A.anio_ejercicio=N.anio_ejercicio\r\n"
												+ "    And A.mes_ejercicio=N.mes_ejercicio\r\n"
												+ "    And A.rfc=N.rfc\r\n"
												+ "    And A.id_delegacion=N.id_delegacion\r\n"
												+ "    And N.id_tipo_paga=4\r\n"
												+ "Group By A.anio_ejercicio, A.mes_ejercicio, A.id_tipo_paga, A.rfc, A.id_delegacion";

	int calcula_isr_par(Integer anio, Integer mes);

	public String STMT_RE_CALCULA_ISR_NON		= "Insert Into gys_externos_isr2 ( anio_ejercicio, mes_ejercicio, id_tipo_paga, id_ordinal,\r\n"
												+ "rfc, id_delegacion, casos, percepciones, isr, id_clave_servicio, id_centro_trabajo, fec_min, fec_max )\r\n"
												+ "Select anio_ejercicio, mes_ejercicio, id_tipo_paga,\r\n"
												+ "(Select NVL(MAX(id_ordinal),0) + 1 From gys_externos_isr2 Where anio_ejercicio = ? And mes_ejercicio = ? And id_tipo_paga = 4) id_ordinal,\r\n"
												+ "rfc, id_delegacion, SUM(casos) casos, SUM(importe) percep, _get_ispt_( SUM(importe) * 2 ) / 2 isr,\r\n"
												+ "MAX(id_clave_servicio) id_clave_servicio, MAX(id_centro_trabajo) id_centro_trabajo, MIN(fec_min) fec_min,  MAX(fec_max) fec_max\r\n"
												+ "From (\r\n"
												+ "  Select\r\n"
												+ "    anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
												+ "    MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
												+ "  From gys_guardias_ext G, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "  Where G.fec_paga = F.fec_pago\r\n"
												+ "    And G.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "    And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "    And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "    And anio_ejercicio = ?\r\n"
												+ "    And mes_ejercicio = ?\r\n"
												+ "    And id_tipo_paga = 4\r\n"
												+ "    And F.fec_pago between ? And ?\r\n"
												+ "    And G.id IN (Select id_guardia From gys_autorizacion_guardias Where estatus2=3)\r\n"
												+ "  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
												+ "  UNION ALL\r\n"
												+ "  Select\r\n"
												+ "    anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
												+ "    MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
												+ "  From gys_suplencias_ext S, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "  Where S.fec_paga = F.fec_pago\r\n"
												+ "    And S.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "    And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "    And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "    And anio_ejercicio = ?\r\n"
												+ "    And mes_ejercicio = ?\r\n"
												+ "    And id_tipo_paga = 4\r\n"
												+ "    And F.fec_pago between ? And ?\r\n"
												+ "    And S.id IN (Select id_suplencia From gys_autorizacion_suplencias Where estatus2=3)\r\n"
												+ "  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
												+ ") Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion";

	int re_calcula_isr_non(Integer anio, Integer mes, String fec_min, String fec_max);

	public String STMT_RE_CALCULA_ISR_PAR		= "Insert Into gys_externos_isr2 ( anio_ejercicio, mes_ejercicio, id_tipo_paga, id_ordinal,\r\n"
												+ "rfc, id_delegacion, casos, percepciones, isr, id_clave_servicio, id_centro_trabajo, fec_min, fec_max )\r\n"
												+ "Select \r\n"
												+ "  A.anio_ejercicio, A.mes_ejercicio, A.id_tipo_paga, \r\n"
												+ "  (Select NVL(MAX(id_ordinal),0) + 1 From gys_externos_isr2 Where anio_ejercicio = ? And mes_ejercicio = ? And id_tipo_paga = 1) id_ordinal,\r\n"
												+ "  A.rfc, A.id_delegacion, SUM(A.casos) casos, SUM(A.percep) percep, SUM(_get_ispt_(percep + NVL(percepciones, 0)) - NVL(N.isr, 0)) isr, \r\n"
												+ "  MAX(A.id_clave_servicio) id_clave_servicio, MAX(A.id_centro_trabajo) id_centro_trabajo, MIN(fec_min) fec_min,  MAX(fec_max) fec_max\r\n"
												+ "From (\r\n"
												+ "  Select anio_ejercicio, mes_ejercicio, id_tipo_paga,\r\n"
												+ "    rfc, id_delegacion, SUM(casos) casos, SUM(importe) percep, _get_ispt_( SUM(importe) * 2 ) / 2 isr,\r\n"
												+ "    MAX(id_clave_servicio) id_clave_servicio, MAX(id_centro_trabajo) id_centro_trabajo, MIN(fec_min) fec_min,  MAX(fec_max) fec_max\r\n"
												+ "  From (\r\n"
												+ "    Select\r\n"
												+ "      anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
												+ "      MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
												+ "    From gys_guardias_ext G, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "    Where G.fec_paga = F.fec_pago\r\n"
												+ "      And G.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "      And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "      And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "      And anio_ejercicio = ?\r\n"
												+ "      And mes_ejercicio = ?\r\n"
												+ "      And id_tipo_paga = 1\r\n"
												+ "      And F.fec_pago between ? And ?\r\n"
												+ "      And G.id IN (Select id_guardia From gys_autorizacion_guardias Where estatus2=3)\r\n"
												+ "    Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
												+ "    UNION ALL\r\n"
												+ "    Select\r\n"
												+ "      anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
												+ "      MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
												+ "    From gys_suplencias_ext S, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "    Where S.fec_paga = F.fec_pago\r\n"
												+ "      And S.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "      And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "      And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "      And anio_ejercicio = ?\r\n"
												+ "      And mes_ejercicio = ?\r\n"
												+ "      And id_tipo_paga = 1\r\n"
												+ "      And F.fec_pago between ? And ?\r\n"
												+ "      And S.id IN (Select id_suplencia From gys_autorizacion_suplencias Where estatus2=3)\r\n"
												+ "    Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
												+ "  ) Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion\r\n"
												+ ") A Left Outer Join (\r\n"
												+ "  Select anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion, SUM(percepciones) percepciones, SUM(isr) isr\r\n"
												+ "  From gys_externos_isr2\r\n"
												+ "  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion\r\n"
												+ ") N\r\n"
												+ "  ON A.anio_ejercicio=N.anio_ejercicio\r\n"
												+ "    And A.mes_ejercicio=N.mes_ejercicio\r\n"
												+ "    And A.rfc=N.rfc\r\n"
												+ "    And A.id_delegacion=N.id_delegacion\r\n"
												+ "    And N.id_tipo_paga=4\r\n"
												+ "Group By A.anio_ejercicio, A.mes_ejercicio, A.id_tipo_paga, A.rfc, A.id_delegacion";

	int re_calcula_isr_par(Integer anio, Integer mes, String fec_min, String fec_max);

	public String QUERY_GET_CIFRAS_ISR			= "Select id_tipo_paga, anio_ejercicio, mes_ejercicio, id_ordinal, SUM(casos) casos, SUM(percepciones) percepciones, SUM(isr) isr,\r\n"
												+ "MIN(fec_min) fec_min, MAX(fec_max) fec_max\r\n"
												+ "From gys_externos_isr2\r\n"
												+ "Where anio_ejercicio = ?\r\n"
												+ "	 And mes_ejercicio = ?\r\n"
												+ "  And id_tipo_paga = ?\r\n"
												+ "Group By id_tipo_paga, anio_ejercicio, mes_ejercicio, id_ordinal";

	List<CifrasDeImpuestos> consultaCifrasDeImpuestos(Integer anio, Integer mes, Integer tipoPaga);

	public String QUERY_GET_CIFRAS_ISR_BY_IDDELEG = "Select id_tipo_paga, anio_ejercicio, mes_ejercicio, id_ordinal, SUM(casos) casos, SUM(percepciones) percepciones, SUM(isr) isr,\r\n"
												+ "MIN(fec_min) fec_min, MAX(fec_max) fec_max\r\n"
												+ "From gys_externos_isr2\r\n"
												+ "Where anio_ejercicio = ?\r\n"
												+ "	 And mes_ejercicio = ?\r\n"
												+ "  And id_tipo_paga = ?\r\n"
												+ "  And id_delegacion = ? \r\n"
												+ "Group By id_tipo_paga, anio_ejercicio, mes_ejercicio, id_ordinal";


	List<CifrasDeImpuestos> consultaCifrasDeImpuestosByIdDeleg(Integer anio, Integer mes, Integer tipoPaga, String idDeleg);

	public String QUERY_GET_CIFRAS_ISR_REP		= "Select id_tipo_paga, anio_ejercicio, mes_ejercicio, id_ordinal, D.id_div_geografica id_representacion, n_div_geografica n_representacion,\r\n"
												+ "  SUM(casos) casos, SUM(percepciones) percepciones, SUM(isr) isr,\r\n"
												+ "  MIN(fec_min) fec_min, MAX(fec_max) fec_max\r\n"
												+ "From gys_externos_isr2 I, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "Where I.id_centro_trabajo = C.id_centro_trabajo\r\n"
												+ "  And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "  And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "	 And anio_ejercicio = ?\r\n"
												+ "	 And mes_ejercicio = ?\r\n"
												+ "  And id_tipo_paga = ?\r\n"
												+ "Group By id_tipo_paga, anio_ejercicio, mes_ejercicio, id_ordinal, D.id_div_geografica, n_div_geografica";

	List<CifrasDeImpuestosPorRepresentacion> consultaCifrasDeImpuestosPorRep(Integer anio, Integer mes, Integer tipoPaga);

	public String QUERY_GET_CIFRAS_ISR_BY_ORDINAL = "Select id_tipo_paga, anio_ejercicio, mes_ejercicio, id_ordinal, SUM(casos) casos, SUM(percepciones) percepciones, SUM(isr) isr,\r\n"
												+ "MIN(fec_min) fec_min, MAX(fec_max) fec_max\r\n"
												+ "From gys_externos_isr2\r\n"
												+ "Where anio_ejercicio = ?\r\n"
												+ "	 And mes_ejercicio = ?\r\n"
												+ "  And id_tipo_paga = ?\r\n"
												+ "  And id_ordinal = ?\r\n"
												+ "Group By id_tipo_paga, anio_ejercicio, mes_ejercicio, id_ordinal";

	CifrasDeImpuestos consultaCifrasDeImpuestosByOrdinal(Integer anio, Integer mes, Integer tipoPaga, Integer id_ordinal);


	public String STMT_ELIMINA_CALCULO_ISR  	= "Delete From gys_externos_isr2 Where anio_ejercicio = ? And mes_ejercicio = ? And id_tipo_paga = ?";

	int elimina_cifras_impuesto(Integer anio, Integer mes, Integer tipoPaga);

	public String STMT_ELIMINA_CALCULO_ISR_BY_DELEG  	= "Delete From gys_externos_isr2 " +
														  "Where anio_ejercicio = ? " +
														  "And mes_ejercicio = ? " +
														  "And id_tipo_paga = ? " +
														  "And id_delegacion = ?";

	int elimina_cifras_impuesto_by_deleg(Integer anio, Integer mes, Integer tipoPaga, String idDeleg);

	public String STMT_ELIMINA_CALCULO_ISR_X_REC = "Delete From gys_externos_isr2 Where anio_ejercicio = ? And mes_ejercicio = ? And id_tipo_paga = ?\r\n"
												+ " And fec_min between ? And ?"
												+ " And fec_max between ? And ?";

	int elimina_cifras_impuesto_x_rec(Integer anio, Integer mes, Integer tipoPaga, String fec_min, String fec_max );

	public String QUERY_GET_DETALLE_CIFRAS_ISR  = "Select * From gys_externos_isr2\r\n"
												+ "Where anio_ejercicio = ?\r\n"
												+ " And mes_ejercicio = ?\r\n"
												+ " And id_tipo_paga = ?\r\n"
												+ " And id_ordinal = ?\r\n";
	List<DetalleCifrasDeImpuestos> getDetalleCifrasDeImpuestos(Integer anio, Integer mes, Integer tipoPaga, Integer id_ordinal);

	public String QUERY_GET_DETALLE_CIFRAS_ISR_REP = "Select I.*, D.id_div_geografica id_representacion, D.n_div_geografica n_representacion \r\n"
												+ "From gys_externos_isr2 I, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "Where I.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "  And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "  And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "  And I.anio_ejercicio = ?\r\n"
												+ "  And I.mes_ejercicio = ?\r\n"
												+ "  And I.id_tipo_paga = ?\r\n"
												+ "  And I.id_ordinal = ?\r\n"
												+ "  And C.id_area_generadora = ( Select id_area_generadora From m4t_delegaciones Where id_div_geografica = ? )";
	List<DetalleCifrasDeImpuestosPorRep> getDetalleCifrasDeImpuestosXRep(Integer anio, Integer mes, Integer tipoPaga, Integer id_ordinal, String id_rep);

	public String QUERY_GET_DETALLE_CIFRAS_ISR_PA = "Select * From gys_externos_isr2\r\n"
												+ "Where anio_ejercicio = ?\r\n"
												+ " And mes_ejercicio = ?\r\n"
												+ " And id_tipo_paga = ?\r\n"
												+ " And id_ordinal = ?\r\n";
	List<DetalleCifrasDeImpuestosConPA> getDetalleCifrasDeImpuestosPA(Integer anio, Integer mes, Integer tipoPaga, Integer id_ordinal);

	// Pruebas Cálculo
	public String STMT_ELIMINA_CALCULO_ISR_X_ORD = "Delete From gys_externos_isr2\r\n"
												+ "Where anio_ejercicio = ? And mes_ejercicio = ? And id_tipo_paga = ?\r\n"
												+ "And id_ordinal = ?";

	int elimina_cifras_impuesto_x_ord(Integer anio, Integer mes, Integer tipoPaga, Integer ord );

	public String STMT_RE_CALCULA_ISR_ORD_NON	= "Insert Into gys_externos_isr2 ( anio_ejercicio, mes_ejercicio, id_tipo_paga, id_ordinal,\r\n"
												+ "rfc, id_delegacion, casos, percepciones, isr, id_clave_servicio, id_centro_trabajo, fec_min, fec_max )\r\n"
												+ "Select anio_ejercicio, mes_ejercicio, id_tipo_paga,\r\n"
												+ "### id_ordinal, rfc, id_delegacion, SUM(casos) casos, SUM(importe) percep, _get_ispt_( SUM(importe) * 2 ) / 2 isr,\r\n"
												+ "MAX(id_clave_servicio) id_clave_servicio, MAX(id_centro_trabajo) id_centro_trabajo, MIN(fec_min) fec_min,  MAX(fec_max) fec_max\r\n"
												+ "From (\r\n"
												+ "  Select\r\n"
												+ "    anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
												+ "    MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
												+ "  From gys_guardias_ext G, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "  Where G.fec_paga = F.fec_pago\r\n"
												+ "    And G.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "    And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "    And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "    And anio_ejercicio = ?\r\n"
												+ "    And mes_ejercicio = ?\r\n"
												+ "    And id_tipo_paga = 4\r\n"
												+ "    And F.fec_pago between ? And ?\r\n"
												+ "    And G.id IN (Select id_guardia From gys_autorizacion_guardias Where estatus2=3)\r\n"
												+ "  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
												+ "  UNION ALL\r\n"
												+ "  Select\r\n"
												+ "    anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
												+ "    MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
												+ "  From gys_suplencias_ext S, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "  Where S.fec_paga = F.fec_pago\r\n"
												+ "    And S.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "    And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "    And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "    And anio_ejercicio = ?\r\n"
												+ "    And mes_ejercicio = ?\r\n"
												+ "    And id_tipo_paga = 4\r\n"
												+ "    And F.fec_pago between ? And ?\r\n"
												+ "    And S.id IN (Select id_suplencia From gys_autorizacion_suplencias Where estatus2=3)\r\n"
												+ "  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
												+ ") Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion";

	int re_calcula_isr_ord_non(Integer anio, Integer mes, String fec_min, String fec_max, Integer ord);

	public String STMT_RE_CALCULA_ISR_ORD_PAR	= "Insert Into gys_externos_isr2 ( anio_ejercicio, mes_ejercicio, id_tipo_paga, id_ordinal,\r\n"
												+ "rfc, id_delegacion, casos, percepciones, isr, id_clave_servicio, id_centro_trabajo, fec_min, fec_max )\r\n"
												+ "Select \r\n"
												+ "  A.anio_ejercicio, A.mes_ejercicio, A.id_tipo_paga, \r\n"
												+ "  ### id_ordinal, A.rfc, A.id_delegacion, SUM(A.casos) casos, SUM(A.percep) percep, SUM(_get_ispt_(percep + NVL(percepciones, 0)) - NVL(N.isr, 0)) isr, \r\n"
												+ "  MAX(A.id_clave_servicio) id_clave_servicio, MAX(A.id_centro_trabajo) id_centro_trabajo, MIN(fec_min) fec_min,  MAX(fec_max) fec_max\r\n"
												+ "From (\r\n"
												+ "  Select anio_ejercicio, mes_ejercicio, id_tipo_paga,\r\n"
												+ "    rfc, id_delegacion, SUM(casos) casos, SUM(importe) percep, _get_ispt_( SUM(importe) * 2 ) / 2 isr,\r\n"
												+ "    MAX(id_clave_servicio) id_clave_servicio, MAX(id_centro_trabajo) id_centro_trabajo, MIN(fec_min) fec_min,  MAX(fec_max) fec_max\r\n"
												+ "  From (\r\n"
												+ "    Select\r\n"
												+ "      anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
												+ "      MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
												+ "    From gys_guardias_ext G, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "    Where G.fec_paga = F.fec_pago\r\n"
												+ "      And G.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "      And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "      And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "      And anio_ejercicio = ?\r\n"
												+ "      And mes_ejercicio = ?\r\n"
												+ "      And id_tipo_paga = 1\r\n"
												+ "      And F.fec_pago between ? And ?\r\n"
												+ "      And G.id IN (Select id_guardia From gys_autorizacion_guardias Where estatus2=3)\r\n"
												+ "    Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
												+ "    UNION ALL\r\n"
												+ "    Select\r\n"
												+ "      anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica id_delegacion, COUNT(*) casos, SUM(importe) importe,\r\n"
												+ "      MAX(id_clave_servicio) id_clave_servicio, MAX(C.id_centro_trabajo) id_centro_trabajo, MIN(F.fec_pago) fec_min,  MAX(F.fec_pago) fec_max\r\n"
												+ "    From gys_suplencias_ext S, gys_fechas_control F, m4t_centros_trab C, m4t_delegaciones D, m4t_area_generadora A\r\n"
												+ "    Where S.fec_paga = F.fec_pago\r\n"
												+ "      And S.id_centro_trabajo=C.id_centro_trabajo\r\n"
												+ "      And C.id_area_generadora = A.id_area_generadora\r\n"
												+ "      And A.id_area_generadora=D.id_area_generadora\r\n"
												+ "      And anio_ejercicio = ?\r\n"
												+ "      And mes_ejercicio = ?\r\n"
												+ "      And id_tipo_paga = 1\r\n"
												+ "      And F.fec_pago between ? And ?\r\n"
												+ "      And S.id IN (Select id_suplencia From gys_autorizacion_suplencias Where estatus2=3)\r\n"
												+ "    Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, D.id_div_geografica\r\n"
												+ "  ) Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion\r\n"
												+ ") A Left Outer Join (\r\n"
												+ "  Select anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion, SUM(percepciones) percepciones, SUM(isr) isr\r\n"
												+ "  From gys_externos_isr2\r\n"
												+ "  Group By anio_ejercicio, mes_ejercicio, id_tipo_paga, rfc, id_delegacion\r\n"
												+ ") N\r\n"
												+ "  ON A.anio_ejercicio=N.anio_ejercicio\r\n"
												+ "    And A.mes_ejercicio=N.mes_ejercicio\r\n"
												+ "    And A.rfc=N.rfc\r\n"
												+ "    And A.id_delegacion=N.id_delegacion\r\n"
												+ "    And N.id_tipo_paga=4\r\n"
												+ "Group By A.anio_ejercicio, A.mes_ejercicio, A.id_tipo_paga, A.rfc, A.id_delegacion";

	int re_calcula_isr_ord_par(Integer anio, Integer mes, String fec_min, String fec_max, Integer ord);

	public String STMT_EXECUTE_SP_PA			= "spm4_gys_pension(?, ?, ?, ?)";

	int calculaPensionAlimenticia(Integer anio, Integer mes, Integer tipoPaga, Integer id_ordinal);

	public String QUERY_GET_DATOS_PA 			= "Select pen.idbolsa, pen.porcentaje, acum.percepciones, pen.cons_benef, acum.rfc, pen.*\r\n"
												+ "From gys_beneficiarios  pen, gys_bolsatrabajo bolsa,  gys_externos_isr2 acum\r\n"
												+ "Where pen.idbolsa = bolsa.id\r\n"
												+ "  And bolsa.rfc = acum.rfc\r\n"
												+ "  And bolsa.iddelegacion = acum.id_delegacion\r\n"
												+ "  And acum.anio_ejercicio = ?\r\n"
												+ "  And acum.mes_ejercicio	= ?\r\n"
												+ "  And acum.id_tipo_paga	= ?\r\n"
												+ "  And acum.id_ordinal = ?\r\n"
												+ "  And pen.fec_inicio <= fec_min\r\n"
												+ "  And (pen.fec_fin >= fec_max or pen.fec_fin is null)\r\n"
												+ "  And bolsa.rfc = ?\r\n"
												+ "Order By cons_benef";

	List<DatosPensionAlimenticia> consultaDatosPA(Integer anio, Integer mes, Integer tipoPaga, Integer id_ordinal, String rfc);	

}